DECLARE
CURSOR C_DCTO IS
SELECT 
ID_PINCRE,
MIN_ARRIENDO,
MAX_ARRIENDO,
PORCRNTAJE
FROM POR_INCREMENTO
WHERE ID_PINCRE = 1;

TYPE T_DCTO IS TABLE OF C_DCTO%ROWTYPE;

V_T_DCTO IS T_DCTO;

begin
FETCH C_DCTO INTO V_T_DCTO;

DBSM_OUTPUT_LINE('ID_PINCRE: '||V_T_DCTO(1).ID_PINCRE);
EXIT WHEN C_DCTO%NOTFOUND;

END;
