DECLARE
V_MIN_ID NUMBER(2);
V_MAX_ID NUMBER(2);

CURSOR C_DCTO(V_X varchar2) IS
SELECT 
ID_PINCRE,
MIN_ARRIENDO,
MAX_ARRIENDO,
PORCRNTAJE
FROM POR_INCREMENTO
WHERE ID_PINCRE = V_X;

TYPE T_DCTO IS RECORD (
    V_ID_P      POR_INCREMENTO.ID_PINCRE%TYPE,
    V_MIN_A     POR_INCREMENTO.MIN_ARRIENDO%TYPE,
    V_MAX_A     POR_INCREMENTO.MAX_ARRIENDO%TYPE,
    V_PORCR     POR_INCREMENTO.PORCRNTAJE%TYPE
);

V_T_DCTO T_DCTO;

BEGIN
    
    SELECT min(id_pincre),max(id_pincre)
        INTO V_MIN_ID,V_MAX_ID
        FROM
    por_incremento;
    
    FOR i IN V_MIN_ID..V_MAX_ID LOOP
          OPEN C_DCTO(i);
            FETCH C_DCTO INTO V_T_DCTO;
            EXIT WHEN C_DCTO%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE(V_T_DCTO.V_ID_P);
            DBMS_OUTPUT.PUT_LINE(V_T_DCTO.V_MIN_A);
            close C_DCTO;
        END LOOP;
    END;